FROM golang:1.22 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o movie-service ./cmd/main

FROM alpine:3.19

WORKDIR /root/

COPY --from=builder /app/movie-service .

EXPOSE 8080

CMD ["./booking-service"]